name: PortMigration Build ESP-IDF

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-port-test:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build esp32s3
        uses: espressif/esp-idf-ci-action@e6f5c74232b1ccd4c97ed641f1e48553853f1fd5 # v1.2.0
        with:
          esp_idf_version: v5.4.1
          target: esp32s3
          path: port/esp_idf/test/port_features

  build-example:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build esp32s3
        uses: espressif/esp-idf-ci-action@e6f5c74232b1ccd4c97ed641f1e48553853f1fd5 # v1.2.0
        with:
          esp_idf_version: v5.4.1
          target: esp32s3
          command: |
            EXAMPLE_APP_PATH=port/esp_idf/test/http_client

            pip install -r requirements.txt

            echo "CONFIG_DEVICE_CRT_DER_FILE=\"main/test/placeholder_device.crt.der\"" >> \
                  ${EXAMPLE_APP_PATH}/sdkconfig.defaults
            echo "CONFIG_DEVICE_KEY_DER_FILE=\"main/test/placeholder_device.key.der\"" >> \
                  ${EXAMPLE_APP_PATH}/sdkconfig.defaults

            idf.py -C $EXAMPLE_APP_PATH build
