name: "Native Simulator and BabbleSim integration tests"

on:
  workflow_dispatch:
    inputs:
      api_url:
        description: "API gateway URL for Golioth backend services"
        required: false
        default: "https://api.golioth.io"
        type: string
      api_key_id:
        description: >-
          Name of GitHub secret containing an API key that will be used to authenticate with the
          Golioth backend
        required: false
        default: "PROD_CI_PROJECT_API_KEY"
        type: string
      coap_gateway_url:
        description: "The CoAP gateway URL to be hardcoded into test firmware"
        required: false
        default: "coaps://coap.golioth.io"
        type: string
  workflow_call:
    inputs:
      api_url:
        description: "API gateway URL for Golioth backend services"
        required: false
        default: "https://api.golioth.io"
        type: string
      api_key_id:
        description: >-
          Name of GitHub secret containing an API key that will be used to authenticate with the
          Golioth backend
        required: false
        default: "PROD_CI_PROJECT_API_KEY"
        type: string
      coap_gateway_url:
        description: "The CoAP gateway URL to be hardcoded into test firmware"
        required: false
        default: "coaps://coap.golioth.io"
        type: string

jobs:
  nsim:
    container: golioth/golioth-zephyr-base:0.17.0-SDK-v0
    env:
      ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains/zephyr-sdk-0.17.0
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          path: pouch

      - name: Init and update west
        run: |
          west init -l pouch --mf west-zephyr.yml
          west update --narrow -o=--depth=1
          git config --global user.email user@git-scm.com
          git config --global user.name "Git User"
          west patch apply

      - name: Build BabbleSim tools
        run: |
          cd tools/bsim && make everything -j $(nproc)

          echo "BSIM_OUT_PATH=$(west topdir)/tools/bsim/" >> $GITHUB_ENV
          echo "BSIM_COMPONENTS_PATH=$(west topdir)/tools/bsim/components/" >> $GITHUB_ENV

      - name: Install pip packages
        run: |
          uv pip install                                  \
            -r pouch/requirements.txt                     \
            -r zephyr/scripts/requirements-base.txt       \
            -r zephyr/scripts/requirements-build-test.txt \
            -r zephyr/scripts/requirements-run-test.txt   \
            cryptography==41.0.7                          \
            pyasn1                                        \
            pyyaml                                        \
            cbor>=1.0.0                                   \
            imgtool>=1.9.0                                \
            jinja2                                        \
            click                                         \
            git+https://github.com/golioth/python-golioth-tools@v0.7.0

      - name: Build and run
        shell: bash
        run: |
          COAP_HOST="${{ inputs.coap_gateway_url }}"
          COAP_HOST="${COAP_HOST#coaps://}"
          COAP_HOST="${COAP_HOST#coap://}"

          export CONFIG_GOLIOTH_COAP_HOST_URI="${{ inputs.coap_gateway_url }}"
          export CONFIG_POUCH_HTTP_GW_URI="gw.${COAP_HOST#coap.}"
          export CONFIG_POUCH_SERVER_CERT_CN="pouch.${COAP_HOST#coap.}"

          zephyr/scripts/twister                                                  \
            -c -v -W                                                              \
            -p native_sim                                                         \
            -p native_sim/native/64                                               \
            -p nrf52_bsim/native                                                  \
            -T pouch/examples/                                                    \
            --pytest-args="--api-url=${{ inputs.api_url }}"                       \
            --pytest-args="--api-key=${{ secrets[inputs.api_key_id] }}"

      - name: Safe upload twister artifacts
        if: success() || failure()
        uses: ./modules/lib/golioth-firmware-sdk/.github/actions/safe-upload-artifacts
        with:
          secrets-json: ${{ toJson(secrets) }}
          name: twister-run-artifacts-bsim
          path: |
            reports/*
            twister-out/**/*.log
            twister-out/**/report.xml
            twister-out/*.xml
            twister-out/*.json
